### ISSUE TITLE
Time Zone Offset on RDO Map

### ISSUE THREAD

**Issue by TheCrazySpy** [jeanropke/RDOMap#119]
**Is your feature request related to a problem? Please describe.**
Not a bug/problem, just a suggestion.

**Describe the solution you'd like**
The "Collectors Map" has a time zone offset customization setting. It would be great to see the same setting on "RDO Map".

**Describe alternatives you've considered**
Time zone support is nice to have, but I have 2 tabs open most of the time so, I can reference the adjusted time on the collectors map or just check time in-game.

Example:
<img width="390" alt="Collector Map Time Zone Example" src="https://user-images.githubusercontent.com/77707573/129086091-ccbe91a6-e7c9-42ea-a5e6-9ead1a77eee6.png">

**Comment by MichalD96** [comment]
This setting actually should be removed or at least renamed, because it only confuses people about how it works and that it has anything related with time zones. It only affects the clock on the map, but have nothing related with your own timezone. 
The main purpose of this setting is to adjust the clock on the map to clock in game, but lately in every session this time is different, so it does not make much sense anyway. This setting should be always set to 0, and only if you see the problem, that clocks doesn't match you should change this value

**Comment by TheCrazySpy** [comment]
Thanks for the explanation. Renaming, adding an explanation when hovering, or just removing it altogether would make sense.
